services:
  - type: web
    name: smart-job-parser
    runtime: docker
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/thisisarjun/smart-job-parser.git
    dockerfilePath: ./Dockerfile
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: 8000
    # Optional: Add environment variables here
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: smart-job-parser-db
    #     property: connectionString

# Optional: Add a database
# databases:
#   - name: smart-job-parser-db
#     plan: free
#     databaseName: smart_job_parser
#     user: admin
