[default]
# API Settings
api_prefix = "/api/v1"
project_name = "Smart Job Parser"

# Server Settings
host = "0.0.0.0"
port = 8000

# RapidAPI Settings
rapidapi_host = "jsearch.p.rapidapi.com"

# Vector Store Settings
vector_store_type = "memory"

# Model Settings
embedding_model = "mxbai-embed-large"

[development]
# Development specific settings
debug = true

[testing]
# Testing specific settings
debug = true
vector_store_type = "memory"

[production]
# Production specific settings
debug = false
